services:
  postgresql:
    image: postgres:16.1
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=shareit
      - TZ=Europe/Moscow
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
  server:
    build: server
    container_name: shareIt-server
    ports:
      - "9090:9090"
    # "зависит от",
    depends_on:
      - postgresql
    # переменные окружения
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - DB_HOST=postgresql
      - DB_PORT=5432
      - TZ=Europe/Moscow
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro
  gateway:
    build: gateway
    container_name: shareIt-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /usr/share/zoneinfo/Europe:/usr/share/zoneinfo/Europe:ro